.TH "SILLY-TEE" "1" "May 23, 2022" "fUN SiLlY pROgrAms f0r fUN sillY Pe0PLe" "Fun Silly User Commands"
.SH NAME
silly-tee \- Tee but silly
.SH SYNOPSIS
\fBsilly-tee\fR
.SH DESCRIPTION
help the user by writing data to stderr and measurements to stdout.
.SH EXIT_STATUS
.TP
\fB0\fR
Success!  a winner is you!

.TP
\fB7\fR
oof.  you need to enter at least something.

.TP
\fB42\fR
um.  maybe

.SH AUTHOR
.P
.nf
Drakey <drackenov@gmail.com>

.SH WWW
https://sillyprograms.com

.SH "SEE ALSO"
.BR tee (1)
