.TH "SILLY-ECHO" "1" "May 22, 2022" "fUN SiLlY pROgrAms f0r fUN sillY Pe0PLe" "Fun Silly User Commands"
.SH NAME
silly-echo \- Echo but silly
.SH SYNOPSIS
\fBsilly-echo\fR [STRING]...
.SH DESCRIPTION
\fBsilly-echo\fR is an implementation of \fBecho\fR(1) but silly
.SH EXIT STATUS
.TP
\fB0\fR
Successful program execution.

.TP
\fB1\fR
Unsuccessful program execution.

.TP
\fB66\fR
The program got anxious. ha ha.

.TP
.B 86
You're not doing it right.

.SH AUTHOR
.P
.RS 2
.nf
Drakey <drackenov@gmail.com>

.SH WWW
https://sillyprograms.com

.SH "SEE ALSO"
.BR echo (1)
