.TH "SILLY-SEQ" "1" "May 24, 2022" "fUN SiLlY pROgrAms f0r fUN sillY Pe0PLe" "Fun Silly User Commands"
.SH NAME
silly-seq \- Seq but silly
.SH SYNOPSIS
\fBsilly-seq\fR LAST
.SH DESCRIPTION
\fBsilly-seq\fR is an implementation of \fBseq\fR(1) but more fun and silly
.SH EXIT STATUS
.TP
\fB0\fR
yay.  you did it

.TP
\fB1\fR
You gotta give it something.

.TP
.B 2
like whatever man. i dunno.

.TP
\fB4\fR
give a number. ha ha.

.SH AUTHOR
.P
.RS 2
.nf
Drakey <drackenov@gmail.com>

.SH WWW
https://sillyprograms.com

.SH "SEE ALSO"
.BR seq (1)

